### ISSUE TITLE
analog channel name size is always zero in AirA entries

### ISSUE THREAD

**Issue by iddq** [imasm/samschanneledit#5]
please take care of channel name size. currently it is always zero.

typedef struct SCMCHANNEL
{
   char         Available;         // flag if entry is available for use
   char         Used;            // flag if entry is used
   char         Skip;            // flag if entry is to be skipped by +/-
   char         Source;            // signal source, see enumeration below
   char         Signal;            // signal type, see enumeration below
   char         Modulation;         // modulation, see enumeration below
   char         Locked;            // channel locked (0=open, 1=locked)
   char         Unknown7;         //*14 | 8
   char         Tuned;            //*0 | 1
   short         Number;            //*customized channel number
   char         Unknown11;         //*-1 | 14
   long         Unknown12;         //*0
   short         Preset;            //*pre-assigned channel number
   unsigned short   Length;            // channel name length (in BYTES!)
   unsigned short   Name[6];         // big-endian Unicode characters
   float         Frequency;         // frequency in MHz with fractions
   char         Unknown36;         //* 1
   char         Unknown37;         //*-1
   unsigned char   Favorites;         // favorites, see definitions below
   unsigned char   CRC;
}   SCMCHANNEL,      *PSCMCHANNEL;

**Comment by imasm** [comment]
Ok, I didn't know about this field. I'm going to fill it.
