### ISSUE TITLE
Removing encrypted channels doesn't work

### ISSUE THREAD

**Issue by keeganrowe** [imasm/samschanneledit#6]
To reproduce:
* Load a channel file that contains some channels that are encrypted and some that are not
* Right-click and select "Remove Encrypted"
* Answer yes to the popup dialog

Actual Result: Encrypted channels are still selected
Expected Result: Encrypted channels are not selected

I've even debugged it and couldn't figure out why it's not working. Sometimes it would unselect the first ~10 that were Encrypted, sometimes not.

I temporarily updated/hacked the code to also do a check for ChannelType == "Radio" and to unselect them too (for my purposes), but that also doesn't work for some reason.

**Comment by imasm** [comment]
Fixed in v0.13 release
